print ("CV ")
print("Nume/Prenume")
print("Gherman Cornelia-Victoria")
print("Data nasterii")
print("08.05.2005")
print("E-mail")
print("corneliagherman2@gmail.com")
print("Nr.de telefon")
print("079799922")
print("Nationalitate")
print("Moldoveanca")
print("Studii")
print("Clasa 1-4 :Liceul Teoretic Mihai Eminescu")
print("Clasa 5-9:Liceul Teoretic Mihai Eminescu")
print("Clasa 10-12:Liceul Teoretic Mihai Eminescu")
print("Acitivitati extrascolare")
print("2010-2015 dansuri de gala")
print("2015-2019 dansuri moderne")
print("2020 club de dezbateri")